name: Checks

# Run this workflow on every commit to every branch.
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # Test build the application.
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

  # Run all unit testing libraries, e2e tests are done seperately.
  # This uses Vitest.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test

  # All style and lint checks:
  # - Prettier check for code format.
  # - ESLint check for code quality.
  style:
    name: Style and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier Check
        run: pnpm run fmt

      - name: Run Lint Check
        run: pnpm run lint
